service: serverless-flask-react

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: ./backend/app.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1

functions:
  app:
    handler: wsgi_handler.handler
    timeout: 60
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'

